In [1]:
import pandas as pd

df = pd.read_csv("../data/crop_recommendation.csv")

print("Umbo la data:", df.shape)
print("\nMajina ya columns:", list(df.columns))
print("\nMifano ya rows 5 za kwanza:")
df.head()

Umbo la data: (2200, 8)

Majina ya columns: ['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall', 'label']

Mifano ya rows 5 za kwanza:

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [2]:
# Angalia ni mazao gani yamo kwenye dataset
print("Idadi ya mazao tofauti:", df['label'].nunique())
print("\nMazao yote:")
print(df['label'].unique())

# Angalia takwimu za wastani (mean) za kila kigezo, kwa kila zao
df.groupby('label')[['N', 'P', 'K', 'ph']].mean()

Idadi ya mazao tofauti: 22

Mazao yote:
<StringArray>
[       'rice',       'maize',    'chickpea', 'kidneybeans',  'pigeonpeas',
   'mothbeans',    'mungbean',   'blackgram',      'lentil', 'pomegranate',
      'banana',       'mango',      'grapes',  'watermelon',   'muskmelon',
       'apple',      'orange',      'papaya',     'coconut',      'cotton',
        'jute',      'coffee']
Length: 22, dtype: str

                  N       P       K        ph
label
apple         20.80  134.22  199.89  5.929663
banana       100.23   82.01   50.05  5.983893
blackgram     40.02   67.47   19.24  7.133952
chickpea      40.09   67.79   79.92  7.336957
coconut       21.98   16.93   30.59  5.976562
coffee       101.20   28.74   29.94  6.790308
cotton       117.77   46.24   19.56  6.912675
grapes        23.18  132.53  200.11  6.025937
jute          78.40   46.86   39.99  6.732778
kidneybeans   20.75   67.54   20.05  5.749411
lentil        18.77   68.36   19.41  6.927932
maize         77.76   48.44   19.79  6.245190
mango         20.07   27.18   29.92  5.766373
mothbeans     21.44   48.01   20.23  6.831174
mungbean      20.99   47.28   19.87  6.723957
muskmelon    100.32   17.72   50.08  6.358805
orange        19.58   16.55   10.01  7.016957
papaya        49.88   59.05   50.04  6.741442
pigeonpeas    20.73   67.73   20.29  5.794175
pomegranate   18.87   18.75   40.21  6.429172
rice          79.89   47.58   39.87  6.425471
watermelon    99.42   17.00   50.22  6.495778

In [3]:
# Hesabu wastani NA kiwango cha tofauti (std) kwa kila zao
takwimu_mazao = df.groupby('label')[['N', 'P', 'K', 'ph']].agg(['mean', 'std'])
takwimu_mazao.head()

                N                  P                 K                  ph  \
             mean        std    mean       std    mean       std      mean
label
apple       20.80  11.863704  134.22  8.139665  199.89  3.320871  5.929663
banana     100.23  11.107241   82.01  7.690339   50.05  3.382591  5.983893
blackgram   40.02  12.664258   67.47  7.151259   19.24  3.188109  7.133952
chickpea    40.09  12.150649   67.79  7.498545   79.92  3.261901  7.336957
coconut     21.98  11.761931   16.93  8.357244   30.59  2.998636  5.976562


                std
label
apple      0.268932
banana     0.270650
blackgram  0.372533
chickpea   0.801127
coconut    0.287632

In [4]:
# Kwa kila zao, hesabu min, max, na mean ya kila kigezo
viwango_vya_mazao = df.groupby('label')[['N', 'P', 'K', 'ph']].agg(['min', 'max', 'mean'])

# Angalia mfano wa zao moja - badilisha 'rice' na zao lililopo kwenye dataset yako
print(viwango_vya_mazao.loc['rice'])

N   min     60.000000
    max     99.000000
    mean    79.890000
P   min     35.000000
    max     60.000000
    mean    47.580000
K   min     35.000000
    max     45.000000
    mean    39.870000
ph  min      5.005307
    max      7.868475
    mean     6.425471
Name: rice, dtype: float64

In [5]:
# 1. Angalia kama kuna data zilizokosekana (missing values)
print("Data zilizokosekana kwa kila kigezo:")
print(df.isnull().sum())

# 2. Angalia takwimu za jumla za kila kigezo cha nambari
print("\nMuhtasari wa takwimu:")
print(df.describe())

# 3. Hakikisha hakuna rows zinazorudia (duplicates)
print("\nIdadi ya rows zinazofanana (duplicates):", df.duplicated().sum())

Data zilizokosekana kwa kila kigezo:
N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

Muhtasari wa takwimu:
                 N            P            K  temperature     humidity  \
count  2200.000000  2200.000000  2200.000000  2200.000000  2200.000000
mean     50.551818    53.362727    48.149091    25.616244    71.481779
std      36.917334    32.985883    50.647931     5.063749    22.263812
min       0.000000     5.000000     5.000000     8.825675    14.258040
25%      21.000000    28.000000    20.000000    22.769375    60.261953
50%      37.000000    51.000000    32.000000    25.598693    80.473146
75%      84.250000    68.000000    49.000000    28.561654    89.948771
max     140.000000   145.000000   205.000000    43.675493    99.981876

                ph     rainfall
count  2200.000000  2200.000000
mean      6.469480   103.463655
std       0.773938    54.958389
min       3.504752    20.211267
25%       5.971693    64.551686
50%       6.425045    94.867624
75%       6.923643   124.267508
max       9.935091   298.560117

Idadi ya rows zinazofanana (duplicates): 0

In [6]:
from sklearn.model_selection import train_test_split

# X = vigezo tunavyotumia kutabiri (features)
X = df[['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall']]

# y = kile tunachotaka kutabiri (target) - jina la zao
y = df['label']

# Gawa data: 80% kufundisha, 20% kupima
X_train, X_test, y_train, y_test = train_test_split(
    X, y, 
    test_size=0.3, 
    random_state=42,
    stratify=y
)

# Thibitisha ukubwa wa kila sehemu
print("Ukubwa wa data ya kufundisha (X_train):", X_train.shape)
print("Ukubwa wa data ya kupima (X_test):", X_test.shape)
print("\nMgawanyo wa mazao kwenye data ya kufundisha:")
print(y_train.value_counts())

Ukubwa wa data ya kufundisha (X_train): (1540, 7)
Ukubwa wa data ya kupima (X_test): (660, 7)

Mgawanyo wa mazao kwenye data ya kufundisha:
label
lentil         70
banana         70
kidneybeans    70
orange         70
mango          70
watermelon     70
mungbean       70
jute           70
coconut        70
rice           70
blackgram      70
papaya         70
coffee         70
pomegranate    70
mothbeans      70
cotton         70
muskmelon      70
maize          70
apple          70
grapes         70
chickpea       70
pigeonpeas     70
Name: count, dtype: int64

In [7]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Unda model - random_state inahakikisha matokeo yanarudiwa sawa kila wakati
model = RandomForestClassifier(random_state=42)

# Fundisha model kwa kutumia data ya training
model.fit(X_train, y_train)

# Tumia model kutabiri kwenye data ya test (ambayo haijawahi kuiona)
y_pred = model.predict(X_test)

# Pima usahihi
accuracy = accuracy_score(y_test, y_pred)
print(f"Usahihi wa model (accuracy): {accuracy:.4f}")
print(f"Kwa asilimia: {accuracy*100:.2f}%")

Usahihi wa model (accuracy): 0.9939
Kwa asilimia: 99.39%

In [8]:
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd

# Ripoti ya kina - inaonyesha utendaji wa model kwa KILA zao kivyake
print("RIPOTI YA KINA (kwa kila zao):")
print(classification_report(y_test, y_pred))

# Confusion Matrix - inaonyesha ni zao gani linachanganywa na zao gani
cm = confusion_matrix(y_test, y_pred, labels=model.classes_)
cm_df = pd.DataFrame(cm, index=model.classes_, columns=model.classes_)

# Onyesha tu mazao yaliyokosewa (siyo yote 22x22, ili iwe rahisi kusoma)
print("\nMazao yenye makosa (kama yapo):")
for zao in model.classes_:
    makosa = cm_df.loc[zao].drop(zao).sum()  # jumla ya makosa kwa zao hili
    if makosa > 0:
        print(f"  {zao}: makosa {makosa}")

RIPOTI YA KINA (kwa kila zao):
              precision    recall  f1-score   support

       apple       1.00      1.00      1.00        30
      banana       1.00      1.00      1.00        30
   blackgram       1.00      0.97      0.98        30
    chickpea       1.00      1.00      1.00        30
     coconut       1.00      1.00      1.00        30
      coffee       1.00      1.00      1.00        30
      cotton       1.00      1.00      1.00        30
      grapes       1.00      1.00      1.00        30
        jute       0.94      1.00      0.97        30
 kidneybeans       1.00      1.00      1.00        30
      lentil       1.00      0.97      0.98        30
       maize       0.97      1.00      0.98        30
       mango       1.00      1.00      1.00        30
   mothbeans       0.97      1.00      0.98        30
    mungbean       1.00      1.00      1.00        30
   muskmelon       1.00      1.00      1.00        30
      orange       1.00      1.00      1.00        30
      papaya       1.00      1.00      1.00        30
  pigeonpeas       1.00      1.00      1.00        30
 pomegranate       1.00      1.00      1.00        30
        rice       1.00      0.93      0.97        30
  watermelon       1.00      1.00      1.00        30

    accuracy                           0.99       660
   macro avg       0.99      0.99      0.99       660
weighted avg       0.99      0.99      0.99       660


Mazao yenye makosa (kama yapo):
  blackgram: makosa 1
  lentil: makosa 1
  rice: makosa 2

In [9]:
import pandas as pd

# Pata umuhimu wa kila kigezo kutoka kwenye model
umuhimu = pd.DataFrame({
    'kigezo': X.columns,
    'umuhimu': model.feature_importances_
}).sort_values('umuhimu', ascending=False)

print(umuhimu)

        kigezo   umuhimu
6     rainfall  0.225824
4     humidity  0.213526
2            K  0.170647
1            P  0.153043
0            N  0.108487
3  temperature  0.076468
5           ph  0.052006

In [10]:
# Panua jedwali kujumuisha vigezo vyote 6 (siyo N,P,K,ph tu kama awali)
viwango_vya_mazao = df.groupby('label')[['N', 'P', 'K', 'temperature', 'humidity', 'ph']].agg(['min', 'max', 'mean'])

# Hifadhi kwenye faili ili tuweze kuitumia baadaye kwenye backend pia
viwango_vya_mazao.to_csv('viwango_vya_mazao_kamili.csv')

# Angalia mfano wa zao moja kuthibitisha muundo ni sahihi
print("Mfano wa 'maize' (badilisha jina kama halipo kwenye orodha yako):")
print(viwango_vya_mazao.loc['maize'])

Mfano wa 'maize' (badilisha jina kama halipo kwenye orodha yako):
N            min      60.000000
             max     100.000000
             mean     77.760000
P            min      35.000000
             max      60.000000
             mean     48.440000
K            min      15.000000
             max      25.000000
             mean     19.790000
temperature  min      18.041855
             max      26.549864
             mean     22.389204
humidity     min      55.282204
             max      74.829137
             mean     65.092249
ph           min       5.513698
             max       6.995844
             mean      6.245190
Name: maize, dtype: float64

In [11]:
def angalia_hali_ya_udongo(zao, usomaji_wa_sasa, jedwali_la_viwango):
    """
    zao: jina la zao (string), mfano 'maize'
    usomaji_wa_sasa: dictionary yenye vigezo 6, mfano:
        {'N': 40, 'P': 30, 'K': 20, 'temperature': 30, 'humidity': 65, 'ph': 5.0}
    jedwali_la_viwango: jedwali letu la min/max/mean kwa kila zao
    
    Inarudisha: orodha (list) ya matatizo yaliyogundulika
    """
    matatizo = []
    
    # Angalia kama zao lipo kwenye jedwali letu
    if zao not in jedwali_la_viwango.index:
        return [f"Samahani, zao '{zao}' halipo kwenye database yetu."]
    
    # Pitia kila kigezo kimoja baada ya kingine
    for kigezo in ['N', 'P', 'K', 'temperature', 'humidity', 'ph']:
        thamani_ya_sasa = usomaji_wa_sasa[kigezo]
        kiwango_cha_chini = jedwali_la_viwango.loc[zao, (kigezo, 'min')]
        kiwango_cha_juu = jedwali_la_viwango.loc[zao, (kigezo, 'max')]
        
        if thamani_ya_sasa < kiwango_cha_chini:
            tofauti = kiwango_cha_chini - thamani_ya_sasa
            matatizo.append({
                'kigezo': kigezo,
                'hali': 'chini_ya_kiwango',
                'thamani_ya_sasa': thamani_ya_sasa,
                'kiwango_kinachohitajika': kiwango_cha_chini,
                'tofauti': round(tofauti, 2)
            })
        elif thamani_ya_sasa > kiwango_cha_juu:
            tofauti = thamani_ya_sasa - kiwango_cha_juu
            matatizo.append({
                'kigezo': kigezo,
                'hali': 'juu_ya_kiwango',
                'thamani_ya_sasa': thamani_ya_sasa,
                'kiwango_kinachohitajika': kiwango_cha_juu,
                'tofauti': round(tofauti, 2)
            })
    
    return matatizo

In [12]:
# Mfano wa usomaji wa sensor - jaribu na maize
usomaji_wangu = {
    'N': 40, 
    'P': 30, 
    'K': 20, 
    'temperature': 30,   # tumeweka juu kidogo kimakusudi kuona kama itagundulika
    'humidity': 65, 
    'ph': 5.0            # tumeweka chini kimakusudi - asidi nyingi
}

matokeo = angalia_hali_ya_udongo('maize', usomaji_wangu, viwango_vya_mazao)

for tatizo in matokeo:
    print(tatizo)

{'kigezo': 'N', 'hali': 'chini_ya_kiwango', 'thamani_ya_sasa': 40, 'kiwango_kinachohitajika': np.int64(60), 'tofauti': np.int64(20)}
{'kigezo': 'P', 'hali': 'chini_ya_kiwango', 'thamani_ya_sasa': 30, 'kiwango_kinachohitajika': np.int64(35), 'tofauti': np.int64(5)}
{'kigezo': 'temperature', 'hali': 'juu_ya_kiwango', 'thamani_ya_sasa': 30, 'kiwango_kinachohitajika': np.float64(26.54986394), 'tofauti': np.float64(3.45)}
{'kigezo': 'ph', 'hali': 'chini_ya_kiwango', 'thamani_ya_sasa': 5.0, 'kiwango_kinachohitajika': np.float64(5.513697923), 'tofauti': np.float64(0.51)}

In [13]:
def hesabu_marekebisho_ya_ph(ph_ya_sasa, ph_lengwa, aina_ya_udongo='tifutifu'):
    """
    ph_ya_sasa: pH ya sasa ya shamba (kutoka sensor)
    ph_lengwa: pH inayohitajika (tunatumia 'mean' ya zao kutoka jedwali letu)
    aina_ya_udongo: 'mchanga', 'tifutifu', au 'mfinyanzi'
    
    Inarudisha: dictionary yenye aina ya marekebisho na kiasi
    """
    # Buffer factor (K) kwa kila aina ya udongo - tani za CaCO3 kwa hekta, kwa unit moja ya pH
    buffer_factor = {
        'mchanga': 1.75,      # wastani wa 1.5-2.0
        'tifutifu': 3.5,      # wastani wa 3.0-4.0
        'mfinyanzi': 6.5      # wastani wa 5.0-8.0
    }
    
    # Sulfur factor (S) kwa kila aina ya udongo - kg za sulfur kwa hekta, kwa unit moja ya pH
    sulfur_factor = {
        'mchanga': 280,
        'tifutifu': 420,
        'mfinyanzi': 560
    }
    
    tofauti_ya_ph = round(ph_lengwa - ph_ya_sasa, 2)
    
    if abs(tofauti_ya_ph) < 0.1:
        # Tofauti ndogo mno, hakuna hatua muhimu ya kuchukua
        return {
            'hatua_inahitajika': False,
            'ujumbe': 'pH iko karibu kabisa na kiwango kinachohitajika.'
        }
    
    if tofauti_ya_ph > 0:
        # pH ya sasa ni CHINI ya lengwa -> udongo una asidi nyingi -> ongeza CHOKAA
        kiasi = round(tofauti_ya_ph * buffer_factor[aina_ya_udongo], 2)
        return {
            'hatua_inahitajika': True,
            'aina_ya_marekebisho': 'chokaa (agricultural lime)',
            'kiasi': kiasi,
            'kipimo': 'tani kwa hekta',
            'sababu': 'Udongo una asidi nyingi kuliko inavyohitajika kwa zao hili.'
        }
    else:
        # pH ya sasa ni JUU ya lengwa -> udongo una alkali nyingi -> ongeza SULFURI
        kiasi = round(abs(tofauti_ya_ph) * sulfur_factor[aina_ya_udongo], 2)
        return {
            'hatua_inahitajika': True,
            'aina_ya_marekebisho': 'sulfuri (elemental sulfur)',
            'kiasi': kiasi,
            'kipimo': 'kg kwa hekta',
            'sababu': 'Udongo una alkali nyingi kuliko inavyohitajika kwa zao hili.'
        }

In [14]:
# Tumia mfano wetu wa awali: maize, ph_ya_sasa = 5.0
ph_lengwa_ya_maize = viwango_vya_mazao.loc['maize', ('ph', 'mean')]
print("pH lengwa ya maize (mean):", round(ph_lengwa_ya_maize, 2))

matokeo_ya_ph = hesabu_marekebisho_ya_ph(
    ph_ya_sasa=5.0, 
    ph_lengwa=ph_lengwa_ya_maize, 
    aina_ya_udongo='tifutifu'
)
print(matokeo_ya_ph)

pH lengwa ya maize (mean): 6.25
{'hatua_inahitajika': True, 'aina_ya_marekebisho': 'chokaa (agricultural lime)', 'kiasi': np.float64(4.38), 'kipimo': 'tani kwa hekta', 'sababu': 'Udongo una asidi nyingi kuliko inavyohitajika kwa zao hili.'}

In [15]:
def hesabu_marekebisho_ya_npk(kigezo, thamani_ya_sasa, thamani_lengwa):
    """
    kigezo: 'N', 'P', au 'K'
    thamani_ya_sasa: usomaji wa sasa kutoka sensor
    thamani_lengwa: kiwango kinachohitajika (mean kutoka jedwali)
    
    Inarudisha: dictionary yenye kiasi cha mbolea kinachohitajika
    """
    factor = {
        'N': 2.5,
        'P': 2.5,
        'K': 2.0
    }
    
    majina_kamili = {
        'N': 'Nitrogen',
        'P': 'Phosphorus',
        'K': 'Potassium'
    }
    
    tofauti = round(thamani_lengwa - thamani_ya_sasa, 2)
    
    if abs(tofauti) < 2:
        return {
            'hatua_inahitajika': False,
            'ujumbe': f'{majina_kamili[kigezo]} iko karibu na kiwango kinachohitajika.'
        }
    
    if tofauti > 0:
        kiasi = round(tofauti * factor[kigezo], 2)
        return {
            'hatua_inahitajika': True,
            'kigezo': majina_kamili[kigezo],
            'hali': 'upungufu',
            'kiasi': kiasi,
            'kipimo': 'kg kwa hekta (nutrient safi)',
            'sababu': f'{majina_kamili[kigezo]} imepungua kuliko inavyohitajika kwa zao hili.'
        }
    else:
        kiasi = round(tofauti * factor[kigezo], 2)
        return {
            'hatua_inahitajika': True,
            'kigezo': majina_kamili[kigezo],
            'hali': 'uzidi',
            'kiasi': abs(kiasi),
            'kipimo': 'kg kwa hekta (punguza kwa kiasi hiki)',
            'sababu': f'{majina_kamili[kigezo]} imezidi kuliko inavyohitajika kwa zao hili.'
        }

In [16]:
# Jaribu na N ya maize (thamani_ya_sasa=40, kutoka mfano wetu wa awali)
N_lengwa_ya_maize = viwango_vya_mazao.loc['maize', ('N', 'mean')]
print("N lengwa ya maize (mean):", round(N_lengwa_ya_maize, 2))

matokeo_ya_N = hesabu_marekebisho_ya_npk('N', thamani_ya_sasa=40, thamani_lengwa=N_lengwa_ya_maize)
print(matokeo_ya_N)

N lengwa ya maize (mean): 77.76
{'hatua_inahitajika': True, 'kigezo': 'Nitrogen', 'hali': 'upungufu', 'kiasi': np.float64(94.4), 'kipimo': 'kg kwa hekta (nutrient safi)', 'sababu': 'Nitrogen imepungua kuliko inavyohitajika kwa zao hili.'}

In [17]:
def toa_ripoti_kamili(zao, usomaji_wa_sasa, jedwali_la_viwango, aina_ya_udongo='tifutifu'):
    """
    Function kuu inayounganisha utambuzi wa matatizo + mahesabu ya marekebisho.
    
    zao: jina la zao, mfano 'maize'
    usomaji_wa_sasa: dictionary ya N,P,K,temperature,humidity,ph
    jedwali_la_viwango: jedwali letu la min/max/mean
    aina_ya_udongo: kwa ajili ya formula ya pH
    
    Inarudisha: dictionary kamili yenye ripoti ya mkulima
    """
    # Hatua 1: Angalia zao lipo kwenye database
    if zao not in jedwali_la_viwango.index:
        return {'hitilafu': f"Zao '{zao}' halipo kwenye database yetu."}
    
    # Hatua 2: Gundua ni vigezo gani vyenye tatizo (tunatumia function ya B2)
    matatizo = angalia_hali_ya_udongo(zao, usomaji_wa_sasa, jedwali_la_viwango)
    
    # Hatua 3: Kama hakuna tatizo lolote
    if len(matatizo) == 0:
        return {
            'zao': zao,
            'hali_ya_jumla': 'Nzuri',
            'ujumbe': f'Hali ya udongo wako inafaa kwa {zao}. Hakuna marekebisho yanayohitajika.',
            'marekebisho': []
        }
    
    # Hatua 4: Kwa kila tatizo lililogundulika, hesabu marekebisho yanayofaa
    marekebisho_yote = []
    
    for tatizo in matatizo:
        kigezo = tatizo['kigezo']
        
        if kigezo == 'ph':
            ph_lengwa = jedwali_la_viwango.loc[zao, ('ph', 'mean')]
            marekebisho = hesabu_marekebisho_ya_ph(
                ph_ya_sasa=usomaji_wa_sasa['ph'],
                ph_lengwa=ph_lengwa,
                aina_ya_udongo=aina_ya_udongo
            )
            marekebisho['kigezo'] = 'pH'
            marekebisho_yote.append(marekebisho)
        
        elif kigezo in ['N', 'P', 'K']:
            thamani_lengwa = jedwali_la_viwango.loc[zao, (kigezo, 'mean')]
            marekebisho = hesabu_marekebisho_ya_npk(
                kigezo=kigezo,
                thamani_ya_sasa=usomaji_wa_sasa[kigezo],
                thamani_lengwa=thamani_lengwa
            )
            marekebisho_yote.append(marekebisho)
        
        else:
            # kwa temperature/humidity - hatuna formula ya kurekebisha (havidhibitiwi na mkulima moja kwa moja)
            marekebisho_yote.append({
                'kigezo': kigezo,
                'hatua_inahitajika': None,
                'ujumbe': f'{kigezo} iko nje ya wigo unaofaa, lakini haiwezi kurekebishwa moja kwa moja shambani (inategemea hali ya hewa).'
            })
    
    return {
        'zao': zao,
        'hali_ya_jumla': 'Kuna matatizo yanayohitaji hatua',
        'idadi_ya_matatizo': len(matatizo),
        'marekebisho': marekebisho_yote
    }

In [18]:
usomaji_wangu = {
    'N': 40, 
    'P': 30, 
    'K': 20, 
    'temperature': 30, 
    'humidity': 65, 
    'ph': 5.0
}

ripoti = toa_ripoti_kamili('maize', usomaji_wangu, viwango_vya_mazao, aina_ya_udongo='tifutifu')

import json
print(json.dumps(ripoti, indent=2, default=str))

{
  "zao": "maize",
  "hali_ya_jumla": "Kuna matatizo yanayohitaji hatua",
  "idadi_ya_matatizo": 4,
  "marekebisho": [
    {
      "hatua_inahitajika": true,
      "kigezo": "Nitrogen",
      "hali": "upungufu",
      "kiasi": 94.4,
      "kipimo": "kg kwa hekta (nutrient safi)",
      "sababu": "Nitrogen imepungua kuliko inavyohitajika kwa zao hili."
    },
    {
      "hatua_inahitajika": true,
      "kigezo": "Phosphorus",
      "hali": "upungufu",
      "kiasi": 46.1,
      "kipimo": "kg kwa hekta (nutrient safi)",
      "sababu": "Phosphorus imepungua kuliko inavyohitajika kwa zao hili."
    },
    {
      "kigezo": "temperature",
      "hatua_inahitajika": null,
      "ujumbe": "temperature iko nje ya wigo unaofaa, lakini haiwezi kurekebishwa moja kwa moja shambani (inategemea hali ya hewa)."
    },
    {
      "hatua_inahitajika": true,
      "aina_ya_marekebisho": "chokaa (agricultural lime)",
      "kiasi": 4.38,
      "kipimo": "tani kwa hekta",
      "sababu": "Udongo una asidi nyingi kuliko inavyohitajika kwa zao hili.",
      "kigezo": "pH"
    }
  ]
}

In [19]:
import joblib

# Hifadhi model ya Random Forest kwenye faili
joblib.dump(model, 'crop_recommendation_model.pkl')

print("Model imehifadhiwa kikamilifu kama 'crop_recommendation_model.pkl'")

Model imehifadhiwa kikamilifu kama 'crop_recommendation_model.pkl'

In [20]:
# Rekebisha muundo wa jedwali kabla ya kuhifadhi - fanya iwe rahisi kusoma tena
viwango_kwa_json = {}

for zao in viwango_vya_mazao.index:
    viwango_kwa_json[zao] = {}
    for kigezo in ['N', 'P', 'K', 'temperature', 'humidity', 'ph']:
        viwango_kwa_json[zao][kigezo] = {
            'min': float(viwango_vya_mazao.loc[zao, (kigezo, 'min')]),
            'max': float(viwango_vya_mazao.loc[zao, (kigezo, 'max')]),
            'mean': float(viwango_vya_mazao.loc[zao, (kigezo, 'mean')])
        }

import json
with open('viwango_vya_mazao.json', 'w') as faili:
    json.dump(viwango_kwa_json, faili, indent=2)

print("Jedwali limehifadhiwa kama JSON - tayari kwa backend")

Jedwali limehifadhiwa kama JSON - tayari kwa backend

In [21]:
def angalia_ph_ya_maji(ph_ya_maji, wigo_wa_chini=6.0, wigo_wa_juu=7.5):
    """
    ph_ya_maji: pH ya sasa ya maji ya umwagiliaji (kutoka sensor)
    wigo_wa_chini/wigo_wa_juu: kiwango cha jumla kinachokubalika kwa mazao mengi
    
    Inarudisha: dictionary yenye tathmini ya pH ya maji
    """
    if ph_ya_maji < wigo_wa_chini:
        return {
            'kigezo': 'pH ya Maji',
            'hatua_inahitajika': True,
            'hali': 'asidi_nyingi',
            'thamani_ya_sasa': ph_ya_maji,
            'wigo_unaofaa': f'{wigo_wa_chini}-{wigo_wa_juu}',
            'ujumbe': 'Maji ya umwagiliaji yana asidi nyingi. Hii inaweza kufanya virutubisho fulani (kama Calcium na Magnesium) visipatikane vizuri kwa mmea.'
        }
    elif ph_ya_maji > wigo_wa_juu:
        return {
            'kigezo': 'pH ya Maji',
            'hatua_inahitajika': True,
            'hali': 'alkali_nyingi',
            'thamani_ya_sasa': ph_ya_maji,
            'wigo_unaofaa': f'{wigo_wa_chini}-{wigo_wa_juu}',
            'ujumbe': 'Maji ya umwagiliaji yana alkali nyingi. Hii inaweza kufanya Iron, Manganese, na Zinc visipatikane vizuri kwa mmea, hata kama vipo kwenye udongo.'
        }
    else:
        return {
            'kigezo': 'pH ya Maji',
            'hatua_inahitajika': False,
            'ujumbe': 'pH ya maji ya umwagiliaji iko ndani ya wigo unaofaa.'
        }

In [22]:
def toa_ripoti_kamili(zao, usomaji_wa_sasa, jedwali_la_viwango, aina_ya_udongo='tifutifu', ph_ya_maji=None):
    """
    Function kuu inayounganisha utambuzi wa matatizo + mahesabu ya marekebisho.
    
    zao: jina la zao, mfano 'maize'
    usomaji_wa_sasa: dictionary ya N,P,K,temperature,humidity,ph (ya UDONGO)
    jedwali_la_viwango: jedwali letu la min/max/mean
    aina_ya_udongo: kwa ajili ya formula ya pH ya udongo
    ph_ya_maji: (HIARI) pH ya maji ya umwagiliaji, kama mkulima anayo
    
    Inarudisha: dictionary kamili yenye ripoti ya mkulima
    """
    if zao not in jedwali_la_viwango.index:
        return {'hitilafu': f"Zao '{zao}' halipo kwenye database yetu."}
    
    matatizo = angalia_hali_ya_udongo(zao, usomaji_wa_sasa, jedwali_la_viwango)
    
    marekebisho_yote = []
    
    for tatizo in matatizo:
        kigezo = tatizo['kigezo']
        
        if kigezo == 'ph':
            ph_lengwa = jedwali_la_viwango.loc[zao, ('ph', 'mean')]
            marekebisho = hesabu_marekebisho_ya_ph(
                ph_ya_sasa=usomaji_wa_sasa['ph'],
                ph_lengwa=ph_lengwa,
                aina_ya_udongo=aina_ya_udongo
            )
            marekebisho['kigezo'] = 'pH ya Udongo'
            marekebisho_yote.append(marekebisho)
        
        elif kigezo in ['N', 'P', 'K']:
            thamani_lengwa = jedwali_la_viwango.loc[zao, (kigezo, 'mean')]
            marekebisho = hesabu_marekebisho_ya_npk(
                kigezo=kigezo,
                thamani_ya_sasa=usomaji_wa_sasa[kigezo],
                thamani_lengwa=thamani_lengwa
            )
            marekebisho_yote.append(marekebisho)
        
        else:
            marekebisho_yote.append({
                'kigezo': kigezo,
                'hatua_inahitajika': None,
                'ujumbe': f'{kigezo} iko nje ya wigo unaofaa, lakini haiwezi kurekebishwa moja kwa moja shambani (inategemea hali ya hewa).'
            })
    
    # MPYA: Angalia pH ya maji, KAMA tu mkulima ameipatia (siyo lazima)
    if ph_ya_maji is not None:
        tathmini_ya_maji = angalia_ph_ya_maji(ph_ya_maji)
        if tathmini_ya_maji['hatua_inahitajika']:
            marekebisho_yote.append(tathmini_ya_maji)
    
    # Kama hakuna tatizo lolote (udongo NA maji vyote viko sawa)
    if len(marekebisho_yote) == 0:
        return {
            'zao': zao,
            'hali_ya_jumla': 'Nzuri',
            'ujumbe': f'Hali ya udongo (na maji, kama yalitolewa) inafaa kwa {zao}. Hakuna marekebisho yanayohitajika.',
            'marekebisho': []
        }
    
    return {
        'zao': zao,
        'hali_ya_jumla': 'Kuna matatizo yanayohitaji hatua',
        'idadi_ya_matatizo': len(marekebisho_yote),
        'marekebisho': marekebisho_yote
    }

In [23]:
usomaji_wangu = {
    'N': 40, 'P': 30, 'K': 20, 
    'temperature': 30, 'humidity': 65, 'ph': 5.0
}

# Kesi 1: BILA taarifa ya maji
ripoti_1 = toa_ripoti_kamili('maize', usomaji_wangu, viwango_vya_mazao, aina_ya_udongo='tifutifu')
print("KESI 1 (bila maji):")
print(json.dumps(ripoti_1, indent=2, default=str))

print("\n" + "="*50 + "\n")

# Kesi 2: NA taarifa ya maji yenye alkali nyingi
ripoti_2 = toa_ripoti_kamili('maize', usomaji_wangu, viwango_vya_mazao, aina_ya_udongo='tifutifu', ph_ya_maji=8.2)
print("KESI 2 (maji yenye alkali nyingi, pH=8.2):")
print(json.dumps(ripoti_2, indent=2, default=str))

KESI 1 (bila maji):
{
  "zao": "maize",
  "hali_ya_jumla": "Kuna matatizo yanayohitaji hatua",
  "idadi_ya_matatizo": 4,
  "marekebisho": [
    {
      "hatua_inahitajika": true,
      "kigezo": "Nitrogen",
      "hali": "upungufu",
      "kiasi": 94.4,
      "kipimo": "kg kwa hekta (nutrient safi)",
      "sababu": "Nitrogen imepungua kuliko inavyohitajika kwa zao hili."
    },
    {
      "hatua_inahitajika": true,
      "kigezo": "Phosphorus",
      "hali": "upungufu",
      "kiasi": 46.1,
      "kipimo": "kg kwa hekta (nutrient safi)",
      "sababu": "Phosphorus imepungua kuliko inavyohitajika kwa zao hili."
    },
    {
      "kigezo": "temperature",
      "hatua_inahitajika": null,
      "ujumbe": "temperature iko nje ya wigo unaofaa, lakini haiwezi kurekebishwa moja kwa moja shambani (inategemea hali ya hewa)."
    },
    {
      "hatua_inahitajika": true,
      "aina_ya_marekebisho": "chokaa (agricultural lime)",
      "kiasi": 4.38,
      "kipimo": "tani kwa hekta",
      "sababu": "Udongo una asidi nyingi kuliko inavyohitajika kwa zao hili.",
      "kigezo": "pH ya Udongo"
    }
  ]
}

==================================================

KESI 2 (maji yenye alkali nyingi, pH=8.2):
{
  "zao": "maize",
  "hali_ya_jumla": "Kuna matatizo yanayohitaji hatua",
  "idadi_ya_matatizo": 5,
  "marekebisho": [
    {
      "hatua_inahitajika": true,
      "kigezo": "Nitrogen",
      "hali": "upungufu",
      "kiasi": 94.4,
      "kipimo": "kg kwa hekta (nutrient safi)",
      "sababu": "Nitrogen imepungua kuliko inavyohitajika kwa zao hili."
    },
    {
      "hatua_inahitajika": true,
      "kigezo": "Phosphorus",
      "hali": "upungufu",
      "kiasi": 46.1,
      "kipimo": "kg kwa hekta (nutrient safi)",
      "sababu": "Phosphorus imepungua kuliko inavyohitajika kwa zao hili."
    },
    {
      "kigezo": "temperature",
      "hatua_inahitajika": null,
      "ujumbe": "temperature iko nje ya wigo unaofaa, lakini haiwezi kurekebishwa moja kwa moja shambani (inategemea hali ya hewa)."
    },
    {
      "hatua_inahitajika": true,
      "aina_ya_marekebisho": "chokaa (agricultural lime)",
      "kiasi": 4.38,
      "kipimo": "tani kwa hekta",
      "sababu": "Udongo una asidi nyingi kuliko inavyohitajika kwa zao hili.",
      "kigezo": "pH ya Udongo"
    },
    {
      "kigezo": "pH ya Maji",
      "hatua_inahitajika": true,
      "hali": "alkali_nyingi",
      "thamani_ya_sasa": 8.2,
      "wigo_unaofaa": "6.0-7.5",
      "ujumbe": "Maji ya umwagiliaji yana alkali nyingi. Hii inaweza kufanya Iron, Manganese, na Zinc visipatikane vizuri kwa mmea, hata kama vipo kwenye udongo."
    }
  ]
}

In [24]:
def angalia_ph_ya_maji(ph_ya_maji, wigo_wa_chini=6.0, wigo_wa_juu=7.5, ujazo_wa_lita=100):
    """
    ph_ya_maji: pH ya sasa ya maji ya umwagiliaji
    wigo_wa_chini/wigo_wa_juu: kiwango cha jumla kinachokubalika
    ujazo_wa_lita: ujazo wa maji unaotibiwa (default lita 100)
    """
    FACTOR_ML_KWA_UNIT = 20   # ml kwa kila lita 100, kwa kila unit ya pH (makadirio ya kawaida)
    
    if ph_ya_maji < wigo_wa_chini:
        tofauti = round(wigo_wa_chini - ph_ya_maji, 2)
        kiasi_ml = round(tofauti * FACTOR_ML_KWA_UNIT * (ujazo_wa_lita / 100), 2)
        return {
            'kigezo': 'pH ya Maji',
            'hatua_inahitajika': True,
            'hali': 'asidi_nyingi',
            'thamani_ya_sasa': ph_ya_maji,
            'wigo_unaofaa': f'{wigo_wa_chini}-{wigo_wa_juu}',
            'aina_ya_marekebisho': 'Potassium Bicarbonate (au Sodium Bicarbonate)',
            'kiasi': kiasi_ml,
            'kipimo': f'ml kwa kila lita {ujazo_wa_lita} za maji',
            'ujumbe': 'Maji yana asidi nyingi. Hii inaweza kufanya Calcium na Magnesium visipatikane vizuri kwa mmea.'
        }
    elif ph_ya_maji > wigo_wa_juu:
        tofauti = round(ph_ya_maji - wigo_wa_juu, 2)
        kiasi_ml = round(tofauti * FACTOR_ML_KWA_UNIT * (ujazo_wa_lita / 100), 2)
        return {
            'kigezo': 'pH ya Maji',
            'hatua_inahitajika': True,
            'hali': 'alkali_nyingi',
            'thamani_ya_sasa': ph_ya_maji,
            'wigo_unaofaa': f'{wigo_wa_chini}-{wigo_wa_juu}',
            'aina_ya_marekebisho': 'Phosphoric Acid (au Citric Acid - salama zaidi)',
            'kiasi': kiasi_ml,
            'kipimo': f'ml kwa kila lita {ujazo_wa_lita} za maji',
            'ujumbe': 'Maji yana alkali nyingi. Hii inaweza kufanya Iron, Manganese, na Zinc visipatikane vizuri kwa mmea.'
        }
    else:
        return {
            'kigezo': 'pH ya Maji',
            'hatua_inahitajika': False,
            'ujumbe': 'pH ya maji ya umwagiliaji iko ndani ya wigo unaofaa.'
        }

In [25]:
usomaji_wangu = {
    'N': 40, 'P': 30, 'K': 20, 
    'temperature': 30, 'humidity': 65, 'ph': 5.0
}

# Jaribu na maji yenye alkali nyingi (pH=8.2), ujazo wa lita 200
ripoti_ya_mwisho = toa_ripoti_kamili(
    'maize', 
    usomaji_wangu, 
    viwango_vya_mazao, 
    aina_ya_udongo='tifutifu', 
    ph_ya_maji=8.2
)

print(json.dumps(ripoti_ya_mwisho, indent=2, default=str))

{
  "zao": "maize",
  "hali_ya_jumla": "Kuna matatizo yanayohitaji hatua",
  "idadi_ya_matatizo": 5,
  "marekebisho": [
    {
      "hatua_inahitajika": true,
      "kigezo": "Nitrogen",
      "hali": "upungufu",
      "kiasi": 94.4,
      "kipimo": "kg kwa hekta (nutrient safi)",
      "sababu": "Nitrogen imepungua kuliko inavyohitajika kwa zao hili."
    },
    {
      "hatua_inahitajika": true,
      "kigezo": "Phosphorus",
      "hali": "upungufu",
      "kiasi": 46.1,
      "kipimo": "kg kwa hekta (nutrient safi)",
      "sababu": "Phosphorus imepungua kuliko inavyohitajika kwa zao hili."
    },
    {
      "kigezo": "temperature",
      "hatua_inahitajika": null,
      "ujumbe": "temperature iko nje ya wigo unaofaa, lakini haiwezi kurekebishwa moja kwa moja shambani (inategemea hali ya hewa)."
    },
    {
      "hatua_inahitajika": true,
      "aina_ya_marekebisho": "chokaa (agricultural lime)",
      "kiasi": 4.38,
      "kipimo": "tani kwa hekta",
      "sababu": "Udongo una asidi nyingi kuliko inavyohitajika kwa zao hili.",
      "kigezo": "pH ya Udongo"
    },
    {
      "kigezo": "pH ya Maji",
      "hatua_inahitajika": true,
      "hali": "alkali_nyingi",
      "thamani_ya_sasa": 8.2,
      "wigo_unaofaa": "6.0-7.5",
      "aina_ya_marekebisho": "Phosphoric Acid (au Citric Acid - salama zaidi)",
      "kiasi": 14.0,
      "kipimo": "ml kwa kila lita 100 za maji",
      "ujumbe": "Maji yana alkali nyingi. Hii inaweza kufanya Iron, Manganese, na Zinc visipatikane vizuri kwa mmea."
    }
  ]
}

In [26]:
import joblib

joblib.dump(model, 'crop_recommendation_model.pkl')
print("✅ Model A imehifadhiwa: crop_recommendation_model.pkl")

✅ Model A imehifadhiwa: crop_recommendation_model.pkl

In [27]:
viwango_kwa_json = {}

for zao in viwango_vya_mazao.index:
    viwango_kwa_json[zao] = {}
    for kigezo in ['N', 'P', 'K', 'temperature', 'humidity', 'ph']:
        viwango_kwa_json[zao][kigezo] = {
            'min': float(viwango_vya_mazao.loc[zao, (kigezo, 'min')]),
            'max': float(viwango_vya_mazao.loc[zao, (kigezo, 'max')]),
            'mean': float(viwango_vya_mazao.loc[zao, (kigezo, 'mean')])
        }

with open('viwango_vya_mazao.json', 'w') as faili:
    json.dump(viwango_kwa_json, faili, indent=2)

print("✅ Jedwali limehifadhiwa: viwango_vya_mazao.json")

✅ Jedwali limehifadhiwa: viwango_vya_mazao.json

In [28]:
%%writefile diagnostic_functions.py
"""
Diagnostic Functions - Model B
Kazi hizi zinatumika kutathmini hali ya udongo na maji ya umwagiliaji
kwa zao maalum lililopandwa, na kutoa ushauri wa marekebisho.

Jinsi ya kutumia (kwa backend):
    from diagnostic_functions import toa_ripoti_kamili, pakua_jedwali_la_viwango
    jedwali = pakua_jedwali_la_viwango('viwango_vya_mazao.json')
    ripoti = toa_ripoti_kamili(zao, usomaji_wa_sasa, jedwali, aina_ya_udongo, ph_ya_maji)
"""

import json


def pakua_jedwali_la_viwango(path_ya_json='viwango_vya_mazao.json'):
    """Inapakua JSON na kuirudisha kama dictionary rahisi."""
    with open(path_ya_json) as faili:
        return json.load(faili)


def angalia_hali_ya_udongo(zao, usomaji_wa_sasa, jedwali_la_viwango):
    matatizo = []
    if zao not in jedwali_la_viwango:
        return [f"Samahani, zao '{zao}' halipo kwenye database yetu."]

    for kigezo in ['N', 'P', 'K', 'temperature', 'humidity', 'ph']:
        thamani_ya_sasa = usomaji_wa_sasa[kigezo]
        kiwango_cha_chini = jedwali_la_viwango[zao][kigezo]['min']
        kiwango_cha_juu = jedwali_la_viwango[zao][kigezo]['max']

        if thamani_ya_sasa < kiwango_cha_chini:
            matatizo.append({
                'kigezo': kigezo, 'hali': 'chini_ya_kiwango',
                'thamani_ya_sasa': thamani_ya_sasa,
                'kiwango_kinachohitajika': kiwango_cha_chini,
                'tofauti': round(kiwango_cha_chini - thamani_ya_sasa, 2)
            })
        elif thamani_ya_sasa > kiwango_cha_juu:
            matatizo.append({
                'kigezo': kigezo, 'hali': 'juu_ya_kiwango',
                'thamani_ya_sasa': thamani_ya_sasa,
                'kiwango_kinachohitajika': kiwango_cha_juu,
                'tofauti': round(thamani_ya_sasa - kiwango_cha_juu, 2)
            })
    return matatizo


def hesabu_marekebisho_ya_ph(ph_ya_sasa, ph_lengwa, aina_ya_udongo='tifutifu'):
    buffer_factor = {'mchanga': 1.75, 'tifutifu': 3.5, 'mfinyanzi': 6.5}
    sulfur_factor = {'mchanga': 280, 'tifutifu': 420, 'mfinyanzi': 560}
    tofauti_ya_ph = round(ph_lengwa - ph_ya_sasa, 2)

    if abs(tofauti_ya_ph) < 0.1:
        return {'hatua_inahitajika': False, 'ujumbe': 'pH iko karibu kabisa na kiwango kinachohitajika.'}
    if tofauti_ya_ph > 0:
        kiasi = round(tofauti_ya_ph * buffer_factor[aina_ya_udongo], 2)
        return {'hatua_inahitajika': True, 'aina_ya_marekebisho': 'chokaa (agricultural lime)',
                'kiasi': kiasi, 'kipimo': 'tani kwa hekta',
                'sababu': 'Udongo una asidi nyingi kuliko inavyohitajika kwa zao hili.'}
    else:
        kiasi = round(abs(tofauti_ya_ph) * sulfur_factor[aina_ya_udongo], 2)
        return {'hatua_inahitajika': True, 'aina_ya_marekebisho': 'sulfuri (elemental sulfur)',
                'kiasi': kiasi, 'kipimo': 'kg kwa hekta',
                'sababu': 'Udongo una alkali nyingi kuliko inavyohitajika kwa zao hili.'}


def hesabu_marekebisho_ya_npk(kigezo, thamani_ya_sasa, thamani_lengwa):
    factor = {'N': 2.5, 'P': 2.5, 'K': 2.0}
    majina_kamili = {'N': 'Nitrogen', 'P': 'Phosphorus', 'K': 'Potassium'}
    tofauti = round(thamani_lengwa - thamani_ya_sasa, 2)

    if abs(tofauti) < 2:
        return {'hatua_inahitajika': False,
                'ujumbe': f'{majina_kamili[kigezo]} iko karibu na kiwango kinachohitajika.'}
    if tofauti > 0:
        kiasi = round(tofauti * factor[kigezo], 2)
        return {'hatua_inahitajika': True, 'kigezo': majina_kamili[kigezo], 'hali': 'upungufu',
                'kiasi': kiasi, 'kipimo': 'kg kwa hekta (nutrient safi)',
                'sababu': f'{majina_kamili[kigezo]} imepungua kuliko inavyohitajika kwa zao hili.'}
    else:
        kiasi = round(tofauti * factor[kigezo], 2)
        return {'hatua_inahitajika': True, 'kigezo': majina_kamili[kigezo], 'hali': 'uzidi',
                'kiasi': abs(kiasi), 'kipimo': 'kg kwa hekta (punguza kwa kiasi hiki)',
                'sababu': f'{majina_kamili[kigezo]} imezidi kuliko inavyohitajika kwa zao hili.'}


def angalia_ph_ya_maji(ph_ya_maji, wigo_wa_chini=6.0, wigo_wa_juu=7.5, ujazo_wa_lita=100):
    FACTOR_ML_KWA_UNIT = 20
    if ph_ya_maji < wigo_wa_chini:
        tofauti = round(wigo_wa_chini - ph_ya_maji, 2)
        kiasi_ml = round(tofauti * FACTOR_ML_KWA_UNIT * (ujazo_wa_lita / 100), 2)
        return {'kigezo': 'pH ya Maji', 'hatua_inahitajika': True, 'hali': 'asidi_nyingi',
                'thamani_ya_sasa': ph_ya_maji, 'wigo_unaofaa': f'{wigo_wa_chini}-{wigo_wa_juu}',
                'aina_ya_marekebisho': 'Potassium Bicarbonate (au Sodium Bicarbonate)',
                'kiasi': kiasi_ml, 'kipimo': f'ml kwa kila lita {ujazo_wa_lita} za maji',
                'ujumbe': 'Maji yana asidi nyingi. Hii inaweza kufanya Calcium na Magnesium visipatikane vizuri.'}
    elif ph_ya_maji > wigo_wa_juu:
        tofauti = round(ph_ya_maji - wigo_wa_juu, 2)
        kiasi_ml = round(tofauti * FACTOR_ML_KWA_UNIT * (ujazo_wa_lita / 100), 2)
        return {'kigezo': 'pH ya Maji', 'hatua_inahitajika': True, 'hali': 'alkali_nyingi',
                'thamani_ya_sasa': ph_ya_maji, 'wigo_unaofaa': f'{wigo_wa_chini}-{wigo_wa_juu}',
                'aina_ya_marekebisho': 'Phosphoric Acid (au Citric Acid - salama zaidi)',
                'kiasi': kiasi_ml, 'kipimo': f'ml kwa kila lita {ujazo_wa_lita} za maji',
                'ujumbe': 'Maji yana alkali nyingi. Hii inaweza kufanya Iron, Manganese, Zinc visipatikane vizuri.'}
    else:
        return {'kigezo': 'pH ya Maji', 'hatua_inahitajika': False,
                'ujumbe': 'pH ya maji ya umwagiliaji iko ndani ya wigo unaofaa.'}


def toa_ripoti_kamili(zao, usomaji_wa_sasa, jedwali_la_viwango, aina_ya_udongo='tifutifu', ph_ya_maji=None):
    if zao not in jedwali_la_viwango:
        return {'hitilafu': f"Zao '{zao}' halipo kwenye database yetu."}

    matatizo = angalia_hali_ya_udongo(zao, usomaji_wa_sasa, jedwali_la_viwango)
    marekebisho_yote = []

    for tatizo in matatizo:
        kigezo = tatizo['kigezo']
        if kigezo == 'ph':
            ph_lengwa = jedwali_la_viwango[zao]['ph']['mean']
            marekebisho = hesabu_marekebisho_ya_ph(usomaji_wa_sasa['ph'], ph_lengwa, aina_ya_udongo)
            marekebisho['kigezo'] = 'pH ya Udongo'
            marekebisho_yote.append(marekebisho)
        elif kigezo in ['N', 'P', 'K']:
            thamani_lengwa = jedwali_la_viwango[zao][kigezo]['mean']
            marekebisho = hesabu_marekebisho_ya_npk(kigezo, usomaji_wa_sasa[kigezo], thamani_lengwa)
            marekebisho_yote.append(marekebisho)
        else:
            marekebisho_yote.append({
                'kigezo': kigezo, 'hatua_inahitajika': None,
                'ujumbe': f'{kigezo} iko nje ya wigo unaofaa, lakini haiwezi kurekebishwa moja kwa moja shambani.'
            })

    if ph_ya_maji is not None:
        tathmini_ya_maji = angalia_ph_ya_maji(ph_ya_maji)
        if tathmini_ya_maji['hatua_inahitajika']:
            marekebisho_yote.append(tathmini_ya_maji)

    if len(marekebisho_yote) == 0:
        return {
            'zao': zao, 'hali_ya_jumla': 'Nzuri',
            'ujumbe': f'Hali ya udongo (na maji, kama yalitolewa) inafaa kwa {zao}. Hakuna marekebisho yanayohitajika.',
            'marekebisho': []
        }

    return {
        'zao': zao, 'hali_ya_jumla': 'Kuna matatizo yanayohitaji hatua',
        'idadi_ya_matatizo': len(marekebisho_yote),
        'marekebisho': marekebisho_yote
    }

Overwriting diagnostic_functions.py

In [29]:
%%writefile -a diagnostic_functions.py


def pakua_jedwali_la_viwango(path_ya_json='viwango_vya_mazao.json'):
    """
    Inapakua faili la JSON na kuligeuza kuwa muundo rahisi wa dictionary
    (SIYO pandas DataFrame - hii inaepuka utata wa multi-level columns).
    
    Inarudisha: dictionary yenye muundo:
        {zao: {kigezo: {'min': ..., 'max': ..., 'mean': ...}}}
    """
    import json
    with open(path_ya_json) as faili:
        return json.load(faili)

Appending to diagnostic_functions.py

In [30]:
from diagnostic_functions import pakua_jedwali_la_viwango, toa_ripoti_kamili

jedwali = pakua_jedwali_la_viwango('viwango_vya_mazao.json')

usomaji_wangu = {
    'N': 40, 'P': 30, 'K': 20,
    'temperature': 30, 'humidity': 65, 'ph': 5.0
}

ripoti = toa_ripoti_kamili('maize', usomaji_wangu, jedwali, aina_ya_udongo='tifutifu', ph_ya_maji=8.2)

import json as jsonlib
print(jsonlib.dumps(ripoti, indent=2, default=str))

{
  "zao": "maize",
  "hali_ya_jumla": "Kuna matatizo yanayohitaji hatua",
  "idadi_ya_matatizo": 5,
  "marekebisho": [
    {
      "hatua_inahitajika": true,
      "kigezo": "Nitrogen",
      "hali": "upungufu",
      "kiasi": 94.4,
      "kipimo": "kg kwa hekta (nutrient safi)",
      "sababu": "Nitrogen imepungua kuliko inavyohitajika kwa zao hili."
    },
    {
      "hatua_inahitajika": true,
      "kigezo": "Phosphorus",
      "hali": "upungufu",
      "kiasi": 46.1,
      "kipimo": "kg kwa hekta (nutrient safi)",
      "sababu": "Phosphorus imepungua kuliko inavyohitajika kwa zao hili."
    },
    {
      "kigezo": "temperature",
      "hatua_inahitajika": null,
      "ujumbe": "temperature iko nje ya wigo unaofaa, lakini haiwezi kurekebishwa moja kwa moja shambani."
    },
    {
      "hatua_inahitajika": true,
      "aina_ya_marekebisho": "chokaa (agricultural lime)",
      "kiasi": 4.38,
      "kipimo": "tani kwa hekta",
      "sababu": "Udongo una asidi nyingi kuliko inavyohitajika kwa zao hili.",
      "kigezo": "pH ya Udongo"
    },
    {
      "kigezo": "pH ya Maji",
      "hatua_inahitajika": true,
      "hali": "alkali_nyingi",
      "thamani_ya_sasa": 8.2,
      "wigo_unaofaa": "6.0-7.5",
      "aina_ya_marekebisho": "Phosphoric Acid (au Citric Acid - salama zaidi)",
      "kiasi": 14.0,
      "kipimo": "ml kwa kila lita 100 za maji",
      "ujumbe": "Maji yana alkali nyingi. Hii inaweza kufanya Iron, Manganese, Zinc visipatikane vizuri."
    }
  ]
}

In [31]:
from sklearn.model_selection import cross_val_score

# Pima model kwa "folds" 5 tofauti (siyo mgawanyo mmoja tu wa train/test)
alama = cross_val_score(model, X, y, cv=5)

print("Alama za kila fold:", alama)
print(f"Wastani wa accuracy: {alama.mean():.4f} (+/- {alama.std():.4f})")

Alama za kila fold: [0.99772727 0.99318182 0.99772727 0.99545455 0.98863636]
Wastani wa accuracy: 0.9945 (+/- 0.0034)

In [32]:
def tengeneza_zao(n, N_range, P_range, K_range, temp_range, humidity_range, ph_range, rainfall_range, jina):
    """Inatengeneza 'n' rows za zao moja, kwa kutumia mipaka ya kisayansi."""
    return pd.DataFrame({
        'N': np.random.uniform(N_range[0], N_range[1], n),
        'P': np.random.uniform(P_range[0], P_range[1], n),
        'K': np.random.uniform(K_range[0], K_range[1], n),
        'temperature': np.random.uniform(temp_range[0], temp_range[1], n),
        'humidity': np.random.uniform(humidity_range[0], humidity_range[1], n),
        'ph': np.random.uniform(ph_range[0], ph_range[1], n),
        'rainfall': np.random.uniform(rainfall_range[0], rainfall_range[1], n),
        'label': jina
    })

print("Function imetengenezwa!")

Function imetengenezwa!

In [33]:
import pandas as pd
import numpy as np
nyanya = tengeneza_zao(
    n=100,
    N_range=(50,90), P_range=(10,25), K_range=(15,27),
    temp_range=(20,27), humidity_range=(50,70),
    ph_range=(6.0,6.8), rainfall_range=(60,130),
    jina='nyanya'
)

print(nyanya.shape)
nyanya.head()

(100, 8)

,N,P,K,temperature,humidity,ph,rainfall,label
0,84.756720,22.766917,25.773247,26.575190,55.589954,6.485686,72.317502,nyanya
1,76.770420,17.820998,22.922610,20.003868,63.847341,6.240775,100.418841,nyanya
2,76.695908,24.439568,15.871763,25.468176,56.501114,6.690188,102.478959,nyanya
3,89.160492,23.572393,18.776166,21.096064,64.615229,6.189866,74.804736,nyanya
4,70.602253,19.160307,21.261180,26.080450,67.189122,6.679587,122.169560,nyanya

In [34]:
n = 100

# --- Mazao Yasiyobadilika (16) ---
bamia = tengeneza_zao(n, (80,120), (20,32), (35,50), (24,32), (60,80), (5.8,6.8), (90,120), 'bamia')
kitunguu_maji = tengeneza_zao(n, (100,140), (18,27), (35,50), (15,25), (60,70), (6.0,6.8), (65,100), 'kitunguu_maji')
maharagwe = tengeneza_zao(n, (20,40), (30,50), (30,50), (18,25), (60,80), (6.0,7.0), (90,130), 'maharagwe')
karoti = tengeneza_zao(n, (60,90), (25,45), (60,100), (16,24), (60,70), (6.0,6.8), (60,100), 'karoti')
mihogo = tengeneza_zao(n, (50,90), (12,20), (25,40), (25,35), (60,80), (5.5,6.5), (100,150), 'mihogo')
pilipili_hoho = tengeneza_zao(n, (80,120), (30,50), (45,75), (20,30), (60,70), (5.5,6.8), (60,100), 'pilipili_hoho')
kitunguu_swaumu = tengeneza_zao(n, (80,100), (20,40), (45,75), (12,24), (60,70), (6.0,7.0), (60,100), 'kitunguu_swaumu')
tangawizi = tengeneza_zao(n, (75,150), (30,70), (30,70), (22,30), (70,90), (5.5,6.5), (150,250), 'tangawizi')
magimbi = tengeneza_zao(n, (60,100), (20,40), (70,110), (21,30), (70,90), (5.5,6.5), (150,250), 'magimbi')
nyanya = tengeneza_zao(n, (50,90), (10,25), (15,27), (20,27), (50,70), (6.0,6.8), (60,130), 'nyanya')
pilipili_manga = tengeneza_zao(n, (100,150), (30,50), (100,150), (23,32), (70,90), (5.5,6.5), (200,300), 'pilipili_manga')
kisamvu = tengeneza_zao(n, (40,80), (15,25), (60,100), (25,35), (60,80), (5.5,6.5), (100,150), 'kisamvu')
kabichi = tengeneza_zao(n, (100,150), (40,60), (80,120), (15,25), (60,80), (6.0,6.8), (60,100), 'kabichi')
maboga = tengeneza_zao(n, (60,100), (30,50), (60,100), (20,30), (60,80), (6.0,6.8), (80,120), 'maboga')
limao = tengeneza_zao(n, (100,150), (30,50), (100,150), (20,30), (60,80), (5.5,6.5), (100,200), 'limao')
kunde = tengeneza_zao(n, (10,30), (30,50), (30,50), (25,35), (50,70), (6.0,7.0), (60,100), 'kunde')

# --- PILIPILI_KALI: batches 3, jina MOJA ---
pk1 = tengeneza_zao(n, (90,120), (35,55), (45,75), (22,32), (60,75), (5.5,6.8), (60,100), 'pilipili_kali')
pk2 = tengeneza_zao(n, (85,115), (33,53), (43,73), (24,34), (60,75), (5.5,6.8), (60,100), 'pilipili_kali')
pk3 = tengeneza_zao(n, (95,125), (37,57), (47,77), (22,32), (60,75), (5.5,6.8), (60,100), 'pilipili_kali')

# --- MBOGA_ZA_MAJANI: batches 5, jina MOJA ---
mz1 = tengeneza_zao(n, (30,50), (50,70), (80,120), (20,30), (60,80), (6.0,7.0), (60,100), 'mboga_za_majani')
mz2 = tengeneza_zao(n, (60,100), (30,50), (60,90), (15,25), (60,80), (6.0,6.8), (60,100), 'mboga_za_majani')
mz3 = tengeneza_zao(n, (80,120), (30,50), (60,90), (15,25), (60,80), (6.0,6.8), (60,100), 'mboga_za_majani')
mz4 = tengeneza_zao(n, (40,70), (30,50), (60,90), (20,30), (60,80), (6.0,7.0), (80,120), 'mboga_za_majani')
mz5 = tengeneza_zao(n, (30,60), (30,50), (60,90), (22,32), (60,80), (6.0,7.0), (80,120), 'mboga_za_majani')

# --- BIRINGANYA: batches 2, jina MOJA ---
bg1 = tengeneza_zao(n, (80,120), (30,50), (60,100), (20,30), (60,80), (5.5,6.8), (80,120), 'biringanya')
bg2 = tengeneza_zao(n, (60,100), (30,50), (60,90), (20,30), (60,80), (5.5,6.8), (80,120), 'biringanya')

df_mazao_ziada_yote = pd.concat([
    bamia, kitunguu_maji, maharagwe, karoti, mihogo, pilipili_hoho,
    kitunguu_swaumu, tangawizi, magimbi, nyanya, pilipili_manga,
    kisamvu, kabichi, maboga, limao, kunde,
    pk1, pk2, pk3, mz1, mz2, mz3, mz4, mz5, bg1, bg2
], ignore_index=True)

print("Jumla ya rows:", len(df_mazao_ziada_yote))
print("Jumla ya mazao:", df_mazao_ziada_yote['label'].nunique())
print(df_mazao_ziada_yote['label'].value_counts())

Jumla ya rows: 2600
Jumla ya mazao: 19
label
mboga_za_majani    500
pilipili_kali      300
biringanya         200
bamia              100
kitunguu_maji      100
maharagwe          100
karoti             100
mihogo             100
pilipili_hoho      100
kitunguu_swaumu    100
tangawizi          100
magimbi            100
nyanya             100
pilipili_manga     100
kisamvu            100
kabichi            100
maboga             100
limao              100
kunde              100
Name: count, dtype: int64

In [35]:
df1 = df[['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall', 'label']].copy()

df_kamili_v4 = pd.concat([df1, df_mazao_ziada_yote], ignore_index=True)
df_kamili_v4 = df_kamili_v4.sample(frac=1, random_state=42).reset_index(drop=True)

print("Jumla ya rows:", len(df_kamili_v4))
print("Jumla ya mazao:", df_kamili_v4['label'].nunique())
print(df_kamili_v4['label'].value_counts())

Jumla ya rows: 4800
Jumla ya mazao: 41
label
mboga_za_majani    500
pilipili_kali      300
biringanya         200
mothbeans          100
kisamvu            100
magimbi            100
tangawizi          100
rice               100
kitunguu_swaumu    100
lentil             100
maboga             100
apple              100
nyanya             100
maharagwe          100
kitunguu_maji      100
chickpea           100
banana             100
karoti             100
muskmelon          100
coconut            100
blackgram          100
kunde              100
pilipili_manga     100
orange             100
pomegranate        100
pigeonpeas         100
mihogo             100
mango              100
grapes             100
papaya             100
limao              100
maize              100
kabichi            100
coffee             100
watermelon         100
jute               100
cotton             100
kidneybeans        100
mungbean           100
bamia              100
pilipili_hoho      100
Name: count, dtype: int64

In [36]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

X_v4 = df_kamili_v4[['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall']]
y_v4 = df_kamili_v4['label']

X_train4, X_test4, y_train4, y_test4 = train_test_split(
    X_v4, y_v4, test_size=0.2, random_state=42, stratify=y_v4
)

model_v4 = RandomForestClassifier(n_estimators=200, random_state=42)
model_v4.fit(X_train4, y_train4)

print("Model A v4 imemaliza kujifunza! Idadi ya mazao:", len(model_v4.classes_))

Model A v4 imemaliza kujifunza! Idadi ya mazao: 41

In [37]:
from sklearn.metrics import classification_report, precision_score, recall_score, f1_score

utabiri_v4 = model_v4.predict(X_test4)

print(classification_report(y_test4, utabiri_v4))

print(f"\nPrecision (macro): {precision_score(y_test4, utabiri_v4, average='macro'):.4f}")
print(f"Recall (macro): {recall_score(y_test4, utabiri_v4, average='macro'):.4f}")
print(f"F1-Score (macro): {f1_score(y_test4, utabiri_v4, average='macro'):.4f}")

                 precision    recall  f1-score   support

          apple       1.00      1.00      1.00        20
          bamia       0.95      0.95      0.95        20
         banana       1.00      1.00      1.00        20
     biringanya       0.73      0.68      0.70        40
      blackgram       1.00      1.00      1.00        20
       chickpea       1.00      1.00      1.00        20
        coconut       1.00      1.00      1.00        20
         coffee       1.00      1.00      1.00        20
         cotton       1.00      1.00      1.00        20
         grapes       1.00      1.00      1.00        20
           jute       0.90      0.95      0.93        20
        kabichi       0.94      0.85      0.89        20
         karoti       0.85      0.55      0.67        20
    kidneybeans       1.00      1.00      1.00        20
        kisamvu       1.00      1.00      1.00        20
  kitunguu_maji       0.95      1.00      0.98        20
kitunguu_swaumu       0.85      0.85      0.85        20
          kunde       1.00      1.00      1.00        20
         lentil       0.95      1.00      0.98        20
          limao       1.00      1.00      1.00        20
         maboga       0.44      0.35      0.39        20
        magimbi       1.00      1.00      1.00        20
      maharagwe       1.00      1.00      1.00        20
          maize       1.00      1.00      1.00        20
          mango       1.00      1.00      1.00        20
mboga_za_majani       0.79      0.95      0.86       100
         mihogo       1.00      1.00      1.00        20
      mothbeans       1.00      0.95      0.97        20
       mungbean       1.00      1.00      1.00        20
      muskmelon       1.00      1.00      1.00        20
         nyanya       1.00      1.00      1.00        20
         orange       1.00      1.00      1.00        20
         papaya       1.00      1.00      1.00        20
     pigeonpeas       1.00      1.00      1.00        20
  pilipili_hoho       0.88      0.35      0.50        20
  pilipili_kali       0.85      0.93      0.89        60
 pilipili_manga       1.00      1.00      1.00        20
    pomegranate       1.00      1.00      1.00        20
           rice       0.95      0.95      0.95        20
      tangawizi       0.95      0.90      0.92        20
     watermelon       1.00      1.00      1.00        20

       accuracy                           0.93       960
      macro avg       0.95      0.93      0.94       960
   weighted avg       0.93      0.93      0.92       960


Precision (macro): 0.9506
Recall (macro): 0.9319
F1-Score (macro): 0.9372

In [38]:
import json

df_wote_kwa_jedwali = pd.concat([
    df[['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'label']],
    df_mazao_ziada_yote[['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'label']]
], ignore_index=True)

jedwali_dict = {}

for zao in df_wote_kwa_jedwali['label'].unique():
    data_ya_zao = df_wote_kwa_jedwali[df_wote_kwa_jedwali['label'] == zao]
    jedwali_dict[zao] = {}
    for kigezo in ['N', 'P', 'K', 'temperature', 'humidity', 'ph']:
        jedwali_dict[zao][kigezo] = {
            'min': float(data_ya_zao[kigezo].min()),
            'max': float(data_ya_zao[kigezo].max()),
            'mean': round(float(data_ya_zao[kigezo].mean()), 2)
        }

with open('../backend/viwango_vya_mazao.json', 'w') as f:
    json.dump(jedwali_dict, f, indent=2)

print(f"Jedwali limehifadhiwa upya! Jumla ya mazao: {len(jedwali_dict)}")
print("\nMfano wa zao moja (bamia):")
print(jedwali_dict['bamia'])

Jedwali limehifadhiwa upya! Jumla ya mazao: 41

Mfano wa zao moja (bamia):
{'N': {'min': 80.64554097194797, 'max': 119.21933011013707, 'mean': 101.32}, 'P': {'min': 20.0399502266028, 'max': 31.880265842910926, 'mean': 26.1}, 'K': {'min': 35.0706001817765, 'max': 49.8383040250761, 'mean': 42.76}, 'temperature': {'min': 24.039265072196397, 'max': 31.94323564032786, 'mean': 27.9}, 'humidity': {'min': 60.08276209488669, 'max': 79.7099207221227, 'mean': 70.27}, 'ph': {'min': 5.813349710855969, 'max': 6.79564973606397, 'mean': 6.31}}

In [39]:
print("Kaggle:", df['label'].nunique())                          # inatarajiwa 22
print("Tanzania (baada ya kuunganisha):", df_mazao_ziada_yote['label'].nunique())  # inatarajiwa 19

Kaggle: 22
Tanzania (baada ya kuunganisha): 19

In [40]:
viwango_tz = df_mazao_ziada_yote.groupby('label')[['N','P','K','temperature','humidity','ph']].agg(['min','max','mean'])
viwango_kaggle = df.groupby('label')[['N','P','K','temperature','humidity','ph']].agg(['min','max','mean'])
viwango_vyote = pd.concat([viwango_kaggle, viwango_tz])

print("JUMLA YA MWISHO:", len(viwango_vyote))

import json
viwango_kwa_json = {}
for zao in viwango_vyote.index:
    viwango_kwa_json[zao] = {
        kigezo: {
            'min': float(viwango_vyote.loc[zao, (kigezo, 'min')]),
            'max': float(viwango_vyote.loc[zao, (kigezo, 'max')]),
            'mean': round(float(viwango_vyote.loc[zao, (kigezo, 'mean')]), 2)
        } for kigezo in ['N','P','K','temperature','humidity','ph']
    }

with open('viwango_vya_mazao.json', 'w') as f:
    json.dump(viwango_kwa_json, f, indent=2)

print("Zimehifadhiwa mazao:", len(viwango_kwa_json))
print("\nOrodha kamili:", sorted(viwango_kwa_json.keys()))

JUMLA YA MWISHO: 41
Zimehifadhiwa mazao: 41

Orodha kamili: ['apple', 'bamia', 'banana', 'biringanya', 'blackgram', 'chickpea', 'coconut', 'coffee', 'cotton', 'grapes', 'jute', 'kabichi', 'karoti', 'kidneybeans', 'kisamvu', 'kitunguu_maji', 'kitunguu_swaumu', 'kunde', 'lentil', 'limao', 'maboga', 'magimbi', 'maharagwe', 'maize', 'mango', 'mboga_za_majani', 'mihogo', 'mothbeans', 'mungbean', 'muskmelon', 'nyanya', 'orange', 'papaya', 'pigeonpeas', 'pilipili_hoho', 'pilipili_kali', 'pilipili_manga', 'pomegranate', 'rice', 'tangawizi', 'watermelon']

In [41]:
import joblib

joblib.dump(model_v4, '../backend/crop_recommendation_model.pkl')
print("Model v2 imehifadhiwa kwenda backend!")
print("Idadi ya mazao:", len(model_v4.classes_))

Model v2 imehifadhiwa kwenda backend!
Idadi ya mazao: 41